code --install-extension batisteo.vscode-django
code --install-extension christian-kohler.path-intellisense
code --install-extension donjayamanne.jupyter
code --install-extension donjayamanne.python-extension-pack
code --install-extension jithurjacob.nbpreviewer
code --install-extension lextudio.restructuredtext
code --install-extension magicstack.MagicPython
code --install-extension ms-python.python
code --install-extension ms-vscode.Go
code --install-extension PeterJausovec.vscode-docker
code --install-extension robertohuertasm.vscode-icons
code --install-extension stkb.rewrap
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension wholroyd.jinja
code --install-extension zhuangtongfa.Material-theme
code --install-extension zxh404.vscode-proto3
